### ISSUE TITLE
What's difference between <astro-island> & <astro-root> tag?

### ISSUE THREAD

**Issue by saurabhck12** [WebDevSimplified/Web-Dev-Simplified-Official-Blog#29]
I am trying to resolve an issue related astro-island. I want to make my react component html to be available to DOM in "astro-root" tag. I don't want astro-island web component.

I am referencing  webDevSimplified blog. I saw in page source of your blog site that it has "astro-root" tag.
I have attached my website screenshot but it has island.

Could you please help me to understand what is actually happening?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/109591787/202140312-565bb40b-a55f-49b7-b4fd-769b25c6a8f9.png">

**Comment by WebDevSimplified** [comment]
I am guessing it is just different versions of Astro. I am on an old version beta version of Astro.

This isn't really the right place to ask this question, though, as I do not know anything about Astro beyond how to use it.
