### ISSUE TITLE
memoization-in-react (2020-05-04)

### ISSUE THREAD

**Issue by GKosheev** [WebDevSimplified/Web-Dev-Simplified-Official-Blog#33]
Hey Kyle.

I've been reading your article where you compare `useCallback` and `useMemo`, and I found that you used the example not in the right way in the following section: [section](https://github.com/WebDevSimplified/Web-Dev-Simplified-Official-Blog/blob/master/src/pages/2020-05/memoization-in-react/index.md#usecallback)

```jsx
useCallback(() => {
  return a + b
}, [a, b])

useMemo(() => {
  return () => a + b
}, [a, b])
```

Shouldn't it be vice versa with a few changes?

```jsx
useCallback(() => {
  return (a, b) => a + b
}, [a, b])

useMemo(() => {
  return a + b
}, [a, b])
```

**Comment by WebDevSimplified** [comment]
What I have written is actually correct.
`useCallback` always returns the memoized version of the function you pass to it which in my case is `() => a + b`.
`useMemo` will return the return value of the function you pass to it which in my case is also `() => a + b`.
The goal of this example was to show how `useMemo` and `useCallback` do the same thing, but work slightly differently.
