### ISSUE TITLE
Newsletter subscription box

### ISSUE THREAD

**Issue by mohittjee** [WebDevSimplified/Web-Dev-Simplified-Official-Blog#42]
While filling up the newsletter subscription box email box input is not visible probably due to text color. Kindly fix it:

Input filled but not visible:

![Screenshot 2024-07-01 233651](https://github.com/WebDevSimplified/Web-Dev-Simplified-Official-Blog/assets/80629130/8adb9adc-88a9-4aee-b892-02bab54e909b)

after selecting all:

![Screenshot 2024-07-01 233713](https://github.com/WebDevSimplified/Web-Dev-Simplified-Official-Blog/assets/80629130/7e07a0d9-3517-4184-8d82-d1265a46e790)

**Comment by WebDevSimplified** [comment]
It looks like this may be related to an extension you have installed. I see an email icon in your browser from an extension which could be changing the font color. When I test this it works just fine for me.

Could you try this in an incognito tab where you have no extensions installed. If it is still causing an issue please let me know what browser you are using and I can try digging deeper into it.

![image](https://github.com/WebDevSimplified/Web-Dev-Simplified-Official-Blog/assets/39717099/1546b58f-8935-4814-8318-87eef66dfc44)

**Comment by mohittjee** [comment]
Yeah it works fine in incognito...sorry about that!
